# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 02:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0005_auto_20160323_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 3, 23, 2, 13, 17, 620302, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
