# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 02:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0006_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('contact_phone', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 12 digits', regex='^\\d{9,12}$')])),
            ],
        ),
    ]
