# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0008_auto_20160323_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
