# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0009_contact_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(default='Contact Us At:', help_text='This will be your greeting message on the Contact Us page.'),
            preserve_default=False,
        ),
    ]
