# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0010_contact_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='time_rsvpd',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 23, 3, 17, 22, 393737, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
