# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0011_rsvp_time_rsvpd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='time_rsvpd',
            field=models.DateField(),
        ),
    ]
