# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0013_auto_20160323_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='time_rsvpd',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
