# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 04:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0014_auto_20160323_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time_of_news',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
