# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool_site', '0016_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AddField(
            model_name='rsvp',
            name='num_guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
